src/api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.ProductList.as_view(), name='product_list'),
    path('products/<slug:pk>', views.ProductDetail.as_view(), name='product_detail'),

    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
]

src/core/apps/chats/urls.py
from django.urls import path

from . import views


app_name = 'chats'

urlpatterns = [
    path('', views.chats_all, name='all'),
    path('<slug:product_id>_<slug:chat_id>/', views.enter_chat, name='detail'),
    path('<slug:product_id>/', views.enter_chat, name='detail'),
    path('<slug:chat_id>/delete', views.delete_chat, name='delete'),
    path('<slug:chat_id>/request-done-deal', views.request_done_deal, name='request_done_deal'),
    path('<slug:chat_id>/request-done-deal-cancel', views.request_done_deal_cancel, name='request_done_deal_cancel'),
    path('<slug:chat_id>/confirm-deal', views.confirm_deal, name='confirm_deal'),
    path('<slug:message_id>/read', views.read_message, name='read_message'),

    path('check-for-messages', views.check_for_new_messages, name='check_for_new_messages'),
    path('check-for-done-deal-request/<slug:chat_id>', views.check_for_done_deal_request, name='check_for_done_deal_request'),
    path('check-for-confirm-deal/<int:customer_id>', views.check_for_confirm_deal, name='check_for_confirm_deal'),
]

src/core/apps/search/urls.py
from django.urls import path

from . import views


app_name = 'search'

urlpatterns = [
    path('', views.main, name='main')
]

src/core/apps/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate-user/<uidb64>/<token>', views.activate_user, name='activate'),
    path('resend-activation-email/<slug:user_id>', views.resend_activation_email, name='resend_activation'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/upvote', views.upvote_feedback, name='upvote_feedback'),
    path('feedback/delete', views.delete_feedback, name='delete_feedback'),

    path('<int:pk>', views.user_profile, name='profile'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('edit-profile/remove-image', views.remove_image, name='remove_image'),

    path('change-password/', views.change_password, name='change_password'),
    path('change-to-new-password/<uidb64>/<uidb64_2>/<token>', views.change_to_new_password, name='confirm_new_password'),

    path('my-wishlist/', views.wishlist, name='wishlist'),
    path('add-to-wishlist/<slug:product_id>', views.add_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<slug:product_id>', views.remove_from_wishlist, name='remove_from_wishlist'),
    
    path('<int:user_reported_id>/report', views.report_user, name='report'),
    path('<slug:user_reported_id>_<slug:message_id>/report', views.report_user, name='report'),

    path('blocked_users/', views.blocked_users, name='blocked'),
    path('blocked_users/remove/<int:user_id>', views.unblock_user, name='unblock'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve

from core.apps.products.views import product_all
from core.apps.users.views import about_page

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('api/auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
]

urlpatterns += i18n_patterns(
    path('', product_all, name='home'),
    path('about/', about_page, name='about_page'),
    path('products/', include('core.apps.products.urls', namespace='products')),
    path('users/', include('core.apps.users.urls', namespace='users')),
    path('chats/', include('core.apps.chats.urls', namespace='chats')),
    path('search/', include('core.apps.search.urls', namespace='search')),
    prefix_default_language=False
)

handler404 = 'core.views.custom_handler404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = [
        *urlpatterns,
        path('__debug__/', include('debug_toolbar.urls'))
    ]
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

src/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css" rel="stylesheet" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <title>{% block title %}SELLor{% endblock title %}</title>
  <style>
    a,
    a:hover {
      color: inherit;
    }
  </style>
  {% block extrahead %}{% endblock extrahead %}
</head>

<body class="bg-dark">
  {% include 'navbar.html' %}
  <div class="wrapper mt-5 pt-3">
    {% if messages %}
    <ul class="d-flex flex-column justify-content-center align-items-center pt-3 pb-1 messages mb-0 gap-2">
      {% for message in messages %}
      {% include 'message.html' %}
      {% endfor %}
    </ul>
    {% endif %}

    {% block content %}{% endblock %}


    {% include 'footer.html' %}
  </div>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js"></script>
  <script>
    function getCookie(cname) {
      let name = cname + '=';
      let decodedCookie = decodeURIComponent(document.cookie);
      let ca = decodedCookie.split(';');
      for (let i = 0; i < ca.length; i++) {
        let c = ca[i];
        while (c.charAt(0) == ' ') {
          c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
          return c.substring(name.length, c.length);
        }
      }
      return '';
    }

    function writeLangToCookie(lang) {
      document.cookie = 'lang=' + lang + '; path=/';
    }

    $(function () {
      origin = window.location.origin;
      path = window.location.pathname;

      langFromCookie = getCookie('lang');
      if (langFromCookie != '') {
        if ((path.includes(langFromCookie)) === false && (langFromCookie !== 'en')) {
          window.location.href = origin + '/' + langFromCookie + path;
        }
      }

      $('.change-language').click(function () {
        lang_code = $(this).data('lang');
        if (langFromCookie != lang_code) {
          writeLangToCookie(lang_code);
          if (lang_code == 'en') {
            url = origin;
            path = path.substring(3);
          } else {
            url = origin + '/' + lang_code;
          }
          url += path;
          window.location.href = url;
        }
      })
    });
  </script>

  {% if request.user.is_authenticated %}
  <script>
    // Call a function every 6000 milliseconds 
    // (OR 6 seconds).
    window.setInterval('check_for_new_messages()', 6000);

    function check_for_new_messages() {
      fetch("{% url 'chats:check_for_new_messages' %}")
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          document.querySelector('#unread-messages-count').innerText = data["newMessagesCount"];
        });
    }
  </script>
  {% endif %}

  {% block javascript %}{% endblock %}
</body>

</html>

src/templates/feedback.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="d-flex justify-content-center pt-4">
  <div class="col-11 col-md-8 col-lg-6">
    <div class="card shadow-0 border" style="background-color: #f0f2f5;">
      <div class="card-body p-4">
        {% if request.user.is_authenticated %}
        <h4 class="text-center">{% trans 'Please feel free to leave any kind of feedback:<br>what did you like or dislike about this app!' %}</h4>
        <form action="" method="post">
          {% csrf_token %}
          <div class="form-outline mt-4">
            <textarea type="text" name="feedback" id="feedback" class="form-control" rows="4" minlength="6"
              maxlength="250" placeholder="{% trans 'Type anything..." required></textarea>
            <label class="form-label" for="feedback">{% trans 'Your thoughts here' %}...</label>
          </div>
          <div class="d-flex justify-content-end">
            <input class="btn btn-primary mt-2 mb-3" type="submit" value="{% trans 'Post' %}" style="font-size: 1rem">
          </div>
        </form>
        {% else %}
        {% endif %}

        {% for post in posts %}
        <div id="feedback{{post.id}}" class="card mb-4">
          <div class="card-body">
            <p>{{ post.text }}</p>
            <div class="row d-flex justify-content-between pt-2">

              <div onclick="window.location='{{post.user.get_absolute_url}}'"
                class="col-12 col-md-6 d-flex flex-row align-items-center" style="cursor: pointer;">
                <img src="{{ post.user.get_image }}" alt="{{ post.user.fullname }}" width="40" height="40" />
                <p class="small mb-0 ms-2">{{ post.user.fullname }}</p>
              </div>

              <div class="col-12 col-md-6 wrap d-flex justify-content-end align-items-{%if request.user == post.user%}center{%else%}end{%endif%}">
                <div class="me-2 text-muted fst-italic mt-auto mt-md-0" style="font-size: 0.84rem">
                  <div class="d-flex align-items-center">
                    {{ post.date_created|date:"H:i, d.m.y" }}
                  </div>
                </div>
                {% if request.user == post.user %}
                <div class="me-1">
                  <a data-index="{{post.id}}" class="delete-btn btn btn-outline-danger">{% trans 'Delete' %}</a>
                </div>
                {% endif %}
                <div id="stats{{post.id}}"
                  class="d-flex flex-row align-items-center {%if request.user in post.upvoted_by.all%}text-primary{%endif%}"
                  style="font-size: 1.2rem;">
                  {% if request.user == post.user %}
                  <i class="far fa-thumbs-up mx-2 fa-xs" style="font-size: 1.2rem; margin-top: -0.16rem;"></i>
                  {% else %}
                  <i data-index="{{post.id}}" title="{% trans 'Upvote' %}" class="fas fa-thumbs-up mx-2 fa-xs upvote-btn"
                    style="cursor: pointer; font-size: 1.2rem; margin-top: -0.16rem;"></i>
                  {% endif %}
                  <p id="upvoteCount{{post.id}}" class="small mb-0"
                    title="{%for user in post.upvoted_by.all%}{{user.fullname}}{%endfor%}">{{ post.upvoted_by.count }}
                  </p>
                </div>
              </div>

            </div>
          </div>
        </div>
        {% empty %}
        <h3 class="text-center py-3">{% trans 'Nothing here' %} :(</h3>
          {% if not request.user.is_authenticated %}
            <h4 class="text-center py-3">{% trans 'You must be' %} <a href="{% url 'users:login' %}" class="text-decoration-underline">{% trans 'logged in</a> to leave feedback' %} :)</h4>
          {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
</div>
{% endblock %}

{% if request.user.is_authenticated %}
{% block javascript %}
<script>
  const getCookie = (name) => {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(";");
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  const upvoteBtns = document.getElementsByClassName('upvote-btn');
  const userId = '{{request.user.id}}';

  for (let i = 0; i < upvoteBtns.length; i++) {
    const upvoteBtn = upvoteBtns[i];

    upvoteBtn.onclick = function upvote(e) {
      const postId = upvoteBtn.dataset.index;
      const url = '{% url "users:upvote_feedback" %}';

      $.ajax({
        type: "POST",
        url: url,
        data: {
          userId: userId,
          postId: postId,
          csrfmiddlewaretoken: getCookie('csrftoken'),
          action: 'POST'
        },
        success: function (json) {
          const stats = document.getElementById(`stats${postId}`);
          const count = document.getElementById(`upvoteCount${postId}`);
          if (json.added) {
            stats.classList.add('text-primary');
            count.innerHTML = json.qty;
          } else if (json.deleted) {
            stats.classList.remove('text-primary');
            count.innerHTML = json.qty;
          } else {
            console.log('error');
          }
        },
        error: function (xhr, errmsg, err) {}
      });
    }
  }

  const deleteBtns = document.getElementsByClassName('delete-btn');
  for (let i = 0; i < deleteBtns.length; i++) {
    const deleteBtn = deleteBtns[i];
    deleteBtn.onclick = function delete_feedback(e) {
      const postId = deleteBtn.dataset.index;
      const url = '{% url "users:delete_feedback" %}';

      $.ajax({
        type: "POST",
        url: url,
        data: {
          userId: userId,
          postId: postId,
          csrfmiddlewaretoken: getCookie('csrftoken'),
          action: 'POST'
        },
        success: function (json) {
          const postDiv = document.getElementById(`feedback${postId}`);
          if (json.deleted) {
            postDiv.remove()
          } else {
            console.log('error');
          }
        },
        error: function (xhr, errmsg, err) {}
      });
    }
  }
</script>
{% endblock javascript %}
{% endif %}

src/templates/footer.html
{% load i18n %}
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/profile.php?id=100020954476710"
        role="button" onmouseover="this.style.color='red'" onmouseout="this.style.color='white'"><i
          class="fab fa-facebook-f"></i></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/yuliannnnnnnnnn/" role="button"
        onmouseover="this.style.color='red'" onmouseout="this.style.color='white'"><i class="fab fa-instagram"></i></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/yulianrudenko" role="button"
        onmouseover="this.style.color='red'" onmouseout="this.style.color='white'"><i class="fab fa-github"></i></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="margin-bottom: 0px;background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright: Yulian Rudenko
  </div>
  <!-- Copyright -->

  <div class="text-center pb-3 text-decoration-underline" style="margin-bottom: 0px;background-color: rgba(0, 0, 0, 0.2);">
    <a href="{% url 'api:product_list' %}">API</a>
  </div>
</footer>

src/templates/message.html
{% load i18n %}
<li class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} w-50 mb-0 fw-bold" role="alert" style="list-style: none;">
  {% autoescape off %}
  {{ message }}
  {% endautoescape %}
</li>

src/templates/navbar.html
{% load i18n %}
{% load static %}
{% load i18n %}
<style>
  @media (min-width: 1050px) and (max-width: 3000px) {
    #search {
      width: 300px;
    }
  }

  .lang {
    background-color: rgb(42, 42, 42);
    color: white;
    font-weight: normal;
  }
  .lang:hover {
    background-color: white;
    color: rgb(42, 42, 42);
    font-weight: bold;
  }
</style>


<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark text-light h6 m-0 px-1">
  <!-- Container wrapper -->
  <div class="container-fluid justify-content-center">
    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'home' %}">
        <font class="h3 p-0 m-0"><i>SELL</i><sub>or</sub> <i class="fa-solid fa-anchor"></i></font><sup><img
            src="{% static 'images/ukr.png' %}" alt="" style="width: 25px" class="ms-1"></sup>
      </a>
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">{% trans 'All Products' %}</a>
        </li>
        <!-- Navbar dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-mdb-toggle="dropdown"
            aria-expanded="false">
            {% trans 'Categories' %}
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for category in categories %}
            <li>
              <a class="dropdown-item ps-1" href="{{ category.get_absolute_url }}">{{ category.name|title }}</a>
            </li>
            {% endfor %}
          </ul>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:dashboard' %}">{% trans 'My Dashboard' %}</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link fst-italic ms-0 ms-lg-1" href="{% url 'users:feedback' %}">{% trans 'Feedback' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link fst-italic" href="{% url 'about_page' %}">{% trans 'About us' %}</a>
        </li>
        <li class="ms-3 nav-item">
          <form action="{% url 'search:main' %}" method="get" class="form-inline my-2 my-lg-0 d-flex gap-1">
            <input name="title" class="form-control mr-sm-2" type="search" placeholder="{% trans 'Search for products..' %}" aria-label="Search" style="font-size: 0.8rem" id="search">
            <button class="btn-sm btn-info my-2 my-sm-0 fw-bold" type="submit" style="font-size: 0.8rem">{% trans 'Search' %}</button>
          </form>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center h4 m-0 p-0 gap-1">

      <!-- CART -->
      <!-- <a class="text-reset me-3" href="" title="Cart">
        <i class="fas fa-shopping-cart"></i>
        <span id="cart-qty" class="badge rounded-pill badge-notification bg-danger">
          0
        </span>
      </a> -->

      <!-- Notifications -->
      <!-- <div class="dropdown" title="Notifications">
        <a class="text-reset me-3 dropdown-toggle hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button"
          data-mdb-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger">
            0
          </span>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
          <li>
            <a class="dropdown-item" href="#">Some news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Another news</a>
          </li>
        </ul>
      </div> -->

      <!-- LANGUAGES  -->
      <div class="dropdown" title="{% trans 'Profile' %}">
        <a class="dropdown-toggle d-flex align-items-center hidden-arrow text-reset me-3" title="{% trans 'Language' %}" id="navbarDropdownMenuAvatar" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-globe"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
          <li class="{% if language.code != LANGUAGE_CODE %}change-language{% endif %} lang text-center h6 mb-0 py-2 dropdown-item" data-lang="{{ language.code }}" style="text-transform: capitalize;">
            {{ language.name_local }}
          </li>
          {% endfor %}
        </ul>
      </div>

      <!-- CHATS -->
      {% if request.user.is_authenticated %}
      <a class="text-reset me-3" href="{% url 'chats:all' %}" title="{% trans 'Chat' %}">
        <i class="fa-regular fa-comments"></i>
        <span id="unread-messages-count" class="badge rounded-pill badge-notification bg-danger">
          {{ request.user.unseen_messages_count }}
        </span>
      </a>
      <!-- WISHLIST -->
      <a class="text-reset me-3" href="{% url 'users:wishlist' %}" title="{% trans 'Wishlist' %}">
        <i class="fa-solid fa-bookmark"></i>
        <span id="wishlist-qty" class="badge rounded-pill badge-notification bg-danger">
          {{ request.user.wishlist.count }}
        </span>
      </a>
      {% endif %}

      <!-- Profile -->
      <div class="dropdown" title="{% trans 'Profile' %}">
        <a class="dropdown-toggle d-flex align-items-center hidden-arrow text-reset" href="{%if request.user.is_authenticated%}{% url 'users:profile' request.user.id%}{%endif%}"
          id="navbarDropdownMenuAvatar" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-user"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
          {% if request.user.is_authenticated %}
          <li class="bg-dark text-light text-center h6 mb-0 py-2 dropdown-item">
            {% trans 'Hi' %}, {{ request.user.first_name }}
            <br>
            {{ request.user.email }}
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'users:profile' request.user.id %}">{% trans 'My profile' %}</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'users:edit_profile' %}">{% trans 'Edit profile' %}</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'users:blocked' %}">{% trans 'Blocked Users' %}</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'users:logout' %}">{% trans 'Log Out' %}</a>
          </li>
          {% else %}
          <li>
            <a class="dropdown-item" href="{% url 'users:login' %}">{% trans 'Log In' %}</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'users:register' %}">{% trans 'Register' %}</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>

src/templates/not_found.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <style>
    body { background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);}
    .error-template {padding: 40px 15px;text-align: center;}
    .error-actions {margin-top:15px;margin-bottom:15px;}
    .error-actions .btn { margin-right:10px; }
  </style>
</head>
<body>
  <div class="container">
      <div class="row">
          <div class="col-md-12">
              <div class="error-template">
                  <h1>
                      Oops!</h1>
                  <h2>
                      404 Not Found</h2>
                  <div class="error-details">
                      {% trans 'Sorry, an error has occurred, Requested page not found' %}!
                  </div>
                  <div class="error-actions">
                      <a href="{% url 'products:home' %}" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                          {% trans 'Take Me Home' %}</a>
                  </div>
              </div>
          </div>
      </div>
  </div>
</body>
</html>