src/api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.ProductList.as_view(), name='product_list'),
    path('products/<slug:pk>', views.ProductDetail.as_view(), name='product_detail'),

    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
]

src/core/apps/products/urls.py
from django.urls import path

from . import views


app_name = 'products'

urlpatterns = [
    path('', views.product_all, name='home'),

    path('add', views.product_add, name='add'),
    path('<slug:pk>', views.product_detail, name='detail'),
    path('<slug:pk>/edit', views.product_edit, name='edit'),
    path('<slug:pk>/edit/remove-image', views.remove_image, name='remove_image'),
    path('<slug:pk>/remove', views.product_remove, name='remove'),

    path('category/<slug:category_name>', views.category, name='category'),
]

src/core/apps/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate-user/<uidb64>/<token>', views.activate_user, name='activate'),
    path('resend-activation-email/<slug:user_id>', views.resend_activation_email, name='resend_activation'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/upvote', views.upvote_feedback, name='upvote_feedback'),
    path('feedback/delete', views.delete_feedback, name='delete_feedback'),

    path('<int:pk>', views.user_profile, name='profile'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('edit-profile/remove-image', views.remove_image, name='remove_image'),

    path('change-password/', views.change_password, name='change_password'),
    path('change-to-new-password/<uidb64>/<uidb64_2>/<token>', views.change_to_new_password, name='confirm_new_password'),

    path('my-wishlist/', views.wishlist, name='wishlist'),
    path('add-to-wishlist/<slug:product_id>', views.add_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<slug:product_id>', views.remove_from_wishlist, name='remove_from_wishlist'),
    
    path('<int:user_reported_id>/report', views.report_user, name='report'),
    path('<slug:user_reported_id>_<slug:message_id>/report', views.report_user, name='report'),

    path('blocked_users/', views.blocked_users, name='blocked'),
    path('blocked_users/remove/<int:user_id>', views.unblock_user, name='unblock'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve

from core.apps.products.views import product_all
from core.apps.users.views import about_page

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('api/auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
]

urlpatterns += i18n_patterns(
    path('', product_all, name='home'),
    path('about/', about_page, name='about_page'),
    path('products/', include('core.apps.products.urls', namespace='products')),
    path('users/', include('core.apps.users.urls', namespace='users')),
    path('chats/', include('core.apps.chats.urls', namespace='chats')),
    path('search/', include('core.apps.search.urls', namespace='search')),
    prefix_default_language=False
)

handler404 = 'core.views.custom_handler404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = [
        *urlpatterns,
        path('__debug__/', include('debug_toolbar.urls'))
    ]
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

src/core/apps/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseForbidden, JsonResponse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.paginator import Paginator
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from core.apps.products.models import Product
from core.apps.chats.models import Chat, Message
from core.utils import redirect_home_if_authenticated, previous_url_or_other, available_products

from .models import UserAccount, ReportUser, Blacklist, Feedback
from .forms import RegistrationForm, LoginForm, UserEditForm, UserChangePasswordForm, ReportForm
from .token import activation_token 


def send_activation_email(request, user):
    current_site = get_current_site(request)
    email_subject = _('Activate your account')
    email_body = render_to_string('users/auth/activate.html', {
        'user': user,
        'domain': current_site,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': activation_token.make_token(user)
    })
    email = EmailMessage(subject=email_subject, body=email_body, from_email=settings.EMAIL_FROM_USER, to=[user.email])
    email.send()

def activate_user(request, uidb64, token):
    uid = force_str(urlsafe_base64_decode(uidb64))
    user = get_object_or_404(UserAccount, pk=uid)
    if activation_token.check_token(user, token):
        user.is_activated = True
        user.save()
        if request.user.is_authenticated:
            logout(request)  
        messages.success(request, _('Email verified, You can now log in!'))
        return redirect('users:login')
    messages.error(request, user.first_name + ', ' + _('something went wrong with your email verification.'))
    return redirect('users:register')

def send_password_confirmation_email(request, user, new_password):
    current_site = get_current_site(request)
    email_subject = {user.fullname} + ', ' + _('confirm that you want to change your password.')
    email_body = render_to_string('users/auth/confirm_new_password.html', {
        'user': user,
        'domain': current_site,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'uid2': urlsafe_base64_encode(force_bytes(new_password)),
        'token': activation_token.make_token(user)
    })
    email = EmailMessage(subject=email_subject, body=email_body, from_email=settings.EMAIL_FROM_USER, to=[user.email])
    email.send()


def change_to_new_password(request, uidb64, uidb64_2, token):
    uid = force_str(urlsafe_base64_decode(uidb64))
    uid2 = force_str(urlsafe_base64_decode(uidb64_2))
    user = get_object_or_404(UserAccount, pk=uid)
    new_password = uid2
    if activation_token.check_token(user, token):
        user.set_password(new_password)
        user.save()
        if request.user.is_authenticated:
            logout(request)
        messages.success(request, _('Password has been changed. Please log in with new password.'))
        return redirect('users:login')
    messages.error(request, _('Something went wrong, please try again.'))
    if request.user.is_authenticated:
        return redirect('users:user_profile', request.user.pk)
    return redirect('users:login')


def about_page(request):
    return render(request, 'about.html')


def feedback(request):
    user = request.user
    if request.method == 'POST':
        if user.is_authenticated:
            if user.feedbacks.all().count() >= 3:
                messages.warning(request, _('You can not post more than 3 feedbacks, please delete a few to post new one.'))
            else:
                text = request.POST.get('feedback')
                if len(text) < 6 or len(text) > 250:
                    messages.warning(request, _('Please provide text between 6 and 250 characters.'))
                else:
                    Feedback.objects.create(user=user, text=text)

    if user.is_authenticated:
        from django.db.models import Value, BooleanField, Case, When
        feedbacks = Feedback.objects.annotate(
            is_users=Case(
                When(user=request.user,
                    then=Value(True)),
                default=Value(False),
                output_field=BooleanField())
        ).order_by('-is_users', '-date_created')
    else:
        feedbacks = Feedback.objects.all().order_by('-date_created')
    context = {'posts': feedbacks}
    return render(request, 'feedback.html', context)


def upvote_feedback(request):
    if request.method == 'POST' and request.POST.get('userId') and request.POST.get('postId'):
        user_id = int(request.POST['userId'])
        feedback_id = int(request.POST['postId'])
        if UserAccount.objects.filter(id=user_id).exists():
            user = UserAccount.objects.filter(id=user_id)[0]
            if Feedback.objects.filter(id=feedback_id).exists():
                fdbck = Feedback.objects.filter(id=feedback_id)[0]
                if user != fdbck.user:
                    if  user not in fdbck.upvoted_by.all():
                        fdbck.upvoted_by.add(user)
                        return JsonResponse({'added': True, 'qty': fdbck.upvoted_by.count()})
                    else:
                        fdbck.upvoted_by.remove(user)
                        return JsonResponse({'deleted': True, 'qty': fdbck.upvoted_by.count()})
    return JsonResponse({'error': '0'})


def delete_feedback(request):
    if request.method == 'POST' and request.POST.get('userId') and request.POST.get('postId'):
        user_id = int(request.POST['userId'])
        feedback_id = int(request.POST['postId'])
        if UserAccount.objects.filter(id=user_id).exists():
            user = UserAccount.objects.filter(id=user_id)[0]
            if Feedback.objects.filter(id=feedback_id).exists():
                fdbck = Feedback.objects.filter(id=feedback_id)[0]
                if user == fdbck.user:
                    fdbck.delete()
                    return JsonResponse({'deleted': True})
    return JsonResponse({'error': '0'})


@redirect_home_if_authenticated
def register(request):
    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST, request.FILES)
        if registration_form.is_valid():
            new_user = registration_form.save(commit=False)
            new_user.set_password(registration_form.cleaned_data['password2'])
            new_user.save()
            send_activation_email(request, new_user)
            messages.success(request, _('Please check your email (including "spam" section), we have sent you message with an activation link.'))
    else:
        registration_form = RegistrationForm() 
    context = {'form': registration_form}
    return render(request, 'users/auth/register.html', context)


@redirect_home_if_authenticated
def login_page(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            creds = {'username': login_form.cleaned_data['email'], 'password': login_form.cleaned_data['password']}
            user = authenticate(**creds)
            if user is not None:
                if user.is_activated == False:
                    url = reverse('users:resend_activation', kwargs={'user_id': user.id}) 
                    link_str =  _('Send activation link again?')
                    login_form.add_error('password', 
                        mark_safe(_('You have not activated your account.') + f' <a href="{url}" class="text-decoration-underline">'
                        + link_str + '</a>'))
                else:
                    login(request, user)
                    messages.success(request, f'{_("Hi")}, {user.first_name}! ' + _('You have been logged in'))
                    next_url = request.GET.get('next')
                    if next_url:
                        return redirect(next_url)
                    return redirect('/')
            else:
                login_form.add_error('password', _('Wrong password.'))
    else:
        login_form = LoginForm()
    return render(request, 'users/auth/login.html', context={'form': login_form})


@redirect_home_if_authenticated
def resend_activation_email(request, user_id):
    if request.user.is_authenticated:
        return redirect('home')
    user = get_object_or_404(UserAccount, id=user_id)
    if user.is_activated == False:
        send_activation_email(request, user)
        messages.success(request, _('Please check your email, message with activation link was sent.'))
    else:
        messages.warning(request, _('Your account is aleady activated.'))
    return redirect('users:login')


def logout_user(request):
    logout(request)
    return redirect('users:login')


def user_profile(request, pk):
    user = get_object_or_404(UserAccount, pk=pk)
    if request.user.is_authenticated:
        if user in request.user.blacklist.blocked_users.all():
            messages.warning(request, _('You blocked this user.'))
            return redirect('users:blocked')
        elif request.user in user.blacklist.blocked_users.all():
            messages.warning(request, _('This user blocked you.'))
            return previous_url_or_other(request, reverse('products:home'))
    user_products = Product.active_products.filter(user=user)
    context = {'user': user, 'user_products':user_products}
    return render(request, 'users/user_profile.html', context)

@login_required
def user_dashboard(request):
    user = request.user

src/templates/users/blocked_users.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<section class="bg-dark">

  <div class="container py-3">
    <div class="row justify-content-center mb-3 g-4">

      {% for user in page_obj %}
      
      <div class="col-md-10 col-xl-9">
        <div class="card shadow-0 border rounded-3">
          <div class="card-body">
            <div class="row">

              <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0 text-center">
                <div class="bg-image hover-zoom ripple rounded ripple-surface">
                  <img src="{{ user.get_image }}" style="height: 220px; object-fit: cover;"
                    class="w-100" />
                  <a href="{{ user.get_absolute_url }}">
                    <div class="hover-overlay">
                      <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                    </div>
                  </a>
                </div>
              </div>
              <div class="col-md-12 col-lg-6 col-xl-9 d-flex flex-column py-3 justify-content-between border-sm-start-none border-start">      
                <div class="">
                  <h2>{{ user.fullname }}</h2>
                </div>
                <div class="">
                  <a href="{% url 'users:unblock' user.id %}" class="btn-lg btn-primary py-4 px-5">
                    <span class="h5">{% trans 'Unblock' %}</span>
                  </a>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
      {% endfor %}

      {% if is_paginated %}
        {% include 'pagination_nav.html' %}
      {% endif %}

    </div>
  </div>
</section>
{% endblock %}

src/templates/users/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<section class="h-100 bg-dark">
  <div class="container h-100 py-4 d-flex justify-content-center text">
    <div class="col-11 col-md-6 card px-4 py-4" style="border-radius: 1rem">

      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="d-flex align-items-center mb-3 pb-1">
          <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
          <span class="h1 fw-bold mb-0">{% trans 'Edit profile' %}</span>
        </div>

        {% if form.errors %}
        <div class="col-md-12 mb-4">
          {% for field in form %}
            {% for error in field.errors %}
            <div class=" py-2 alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
          {% endfor %}
        </div>
        {% endif %}

        <div class="mx-0 mt-2 mb-4 row w-100">
          <div class="col-12 d-flex flex-column align-items-center">
            <img id="profileImage" src="{{ user.get_image }}" alt="Generic placeholder image"
              class="img-fluid img-thumbnail mt-2 mb-4" style="width: 150px; z-index: 1">
          </div>
          <div class="col-12 d-flex flex-column align-items-center">
            {{ form.image }}
          </div>
          <div class="col-12 d-flex flex-column align-items-center mt-2 py-2">
            <a href="{% url 'users:remove_image' %}" class="btn btn-danger">{% trans 'Remove image' %}</a>
          </div>
        </div>

        <div class="form-outline mb-2">
          {{ form.first_name }}
          <label class="form-label">{% trans 'First name' %}</label>
        </div>
        <div class="form-outline mb-4">
          {{ form.last_name }}
          <label class="form-label">{% trans 'Last name' %}</label>
        </div>

        <div class="form-outline mb-1">
          {{ form.phone }}
          <label class="form-label">{% trans 'Phone' %} +48..</label>
        </div>

        <div class="mb-4">
          <label class="label text-decoration-underline">{% trans 'Location' %}</label>
          {{ form.location }}
        </div>

        <div class="pt-1 mb-4">
          <button class="btn btn-dark btn-lg btn-block" type="submit">{% trans 'Submit' %}</button>
        </div>

        <a
            href="{% url 'users:change_password' %}" class="h5 mb-5 pb-lg-2 text-decoration-underline" style="color: #393f81;">{% trans 'Want to change password? Click here' %}.</a>
      </form>

    </div>
  </div>
</section>
{% endblock %}

{% block javascript %}
<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#profileImage').attr('src', e.target.result).width(150).height(200);
      };

      reader.readAsDataURL(input.files[0]);
    }
  }

  function validateFileType(){
      var fileName = document.getElementById("profileImageInput").value;
      var idxDot = fileName.lastIndexOf(".") + 1;
      var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
      if (extFile=="jpg" || extFile=="jpeg" || extFile=="png"){
          //TO DO
      }else{
          alert("{% trans 'Only jpg/jpeg and png files are allowed' %}!");
          window.location.reload()
      }   
  }
</script>
{% endblock javascript %}

src/templates/users/user_profile.html
{% extends 'base.html' %}
{% load my_tags %}
{% load i18n %}

{% block content %}
<section class="h-100 gradient-custom-2">
  <div class="container py-4 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">

          <div class="d-flex flex-column flex-md-row justify-content-between rounded-top text-white" style="background-color: #000;">
            <div class="d-flex flex-column flex-md-row px-3 py-3 gap-3 align-items-center">
              <img src="{{ user.get_image }}"
                alt="Profile image" class="img-fluid img-thumbnail w-75" style="max-height: 350px"
                >
                <div class="d-flex flex-column justify-content-end text-center">
                  <h4>{{ user.fullname }}</h4>
                  <h5 class="text-muted">
                    {% trans 'from' %} 
                    <i class="text-light">{{ user.location }}</i>
                  </h5>
                </div>
            </div>

            <div class="d-flex justify-content-center align-items-center px-5 py-2">
              <div class="d-flex flex-row gap-1 gap-md-1 flex-md-column">
                {% if request.user == user %}
                <a href="{% url 'users:edit_profile' %}" type="button" class="btn-lg btn-dark fw-bold text-center" data-mdb-ripple-color="dark"
                  style="z-index: 1;">
                  {% trans 'Edit profile' %}
                </a>
                <a href="{% url 'products:add' %}" type="button" class="btn-lg btn-info mt-0 mt-md-1 fw-bold text-center"
                  style="z-index: 1;">
                  {% trans 'Add product' %}
                </a>
                {% else %}
                <a href="{% url 'users:report' user.id %}" type="button" class="btn-lg fw-bold text-center btn-danger mt-0 mt-md-1 text-center"
                  style="z-index: 1;">
                  {% trans 'Report user' %}
                </a>
                {% endif %}
              </div>
            </div>
          </div>

          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-center text-center py-1 gap-3 h5">

              <div>
                <p class="mb-1 h5">{{ user_products.count }}</p>
                <p class="small text-muted mb-0">{% trans 'Active Products' %}</p>
              </div>
              <div class="px-3">
                <p class="mb-1 h5">{{ user.sold_count }}</p>
                <p class="small text-muted mb-0">{% trans 'Sold' %}</p>
              </div>
              <div>
                <p class="mb-1 h5">{{ user.purchased_count }}</p>
                <p class="small text-muted mb-0">{% trans 'Purchased' %}</p>
              </div>
            </div>
          </div>

          
          <div class="card-body p-4 text-black">
            <div class="d-flex justify-content-between align-items-center mb-4">
              <p class="lead fw-bold mb-0">{% trans 'Products' %}</p>
            </div>
            
            <div class="row hidden-md-up">
              {% if user == request.user %}
                {% for product in user_products %}
                <div class="col-md-4">
                    <div class="card">
                      <div class="card-block">
                        <a href="{{ product.get_absolute_url }}" style="color: inherit;">
                          <img src="{{ product.get_image }}" class="card-img-top" style="max-height: 340px; object-fit: cover;" alt="product">
                        </a>
                        <div class="p-2">
                          <a href="{{ product.get_absolute_url }}" style="color: inherit;">
                            <h4 class="card-title">{{ product.title|title }}</h4>
                          </a>
                          <h6 class="card-subtitle text-muted">{% trans 'Category' %}: {{ product.category }}</h6>
                          {% if product.description %}
                            <p class="card-text">{{ product.description|truncatechars:45 }}</p>
                          {% else %}
                            <p class="card-text">&nbsp;</p>
                          {% endif %}
                          {% if product.discount_price %}
                          <div class="px-2">
                            <span class="text-danger"><s>{{ product.price }} zł</s></span>
                            <span class="card-text h5">{{ product.discount_price }} zł</span>
                          </div>
                          {% else %}
                          <div class="px-2">
                            <span class="mb-1 me-1 h5">{{ product.price }} zł</span>
                          </div>
                          {% endif %}
                          <div class="d-flex justify-content-around mt-4 mb-2 px-1">
                            <a href="{% url 'products:edit' product.id %}" class="btn-lg btn-primary">{% trans 'Edit' %}</a>
                            <a href="{% url 'products:remove' product.id %}" class="btn-lg btn-danger">{% trans 'Delete' %}</a>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
                {% empty %}
                <div class="w-100 pt-4">
                <h4 class="text-center"> {% trans 'You are not selling anything yet' %}.</h4>
                </div>
                {% endfor %}
              {% else %}
                {% for product in user_products %}
                <div class="col-md-4">
                  <a href="{{ product.get_absolute_url }}" style="color: inherit;">
                    <div class="card">
                      <div class="card-block">
                        <img src="{{ product.get_image }}" class="card-img-top" style="max-height: 340px; object-fit: cover;" alt="product">
                        <div class="p-2">
                          <h4 class="card-title">{{ product.title|title }}</h4>
                          <h6 class="card-subtitle text-muted">{% trans 'Category' %}: {{ product.category }}</h6>
                          {% if product.description %}
                            <p class="card-text">{{ product.description|truncatechars:45 }}</p>
                          {% else %}
                            <p class="card-text">&nbsp;</p>
                          {% endif %}
                          {% if product.discount_price %}
                          <div class="text-end">
                            <span class="text-danger"><s>{{ product.price }} zł</s></span>
                            <span class="card-text h5">{{ product.discount_price }} zł</span>
                          </div>
                          {% else %}
                          <div class="text-end">
                            <span class="mb-1 h5">{{ product.price }} zł</span>
                          </div>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </a>
                </div>
                {% empty %}
                <div class="w-100 pt-4">
                <h4 class="text-center"> {% trans 'You are not selling anything yet' %}.</h4>
                </div>
                {% endfor %}
              {% endif %}
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

src/templates/users/wishlist.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}
{% load i18n %}

{% block content %}
  <section class="bg-dark">
    <div class="container py-3">
      <h1 class="text-center text-light">{% trans 'Wishlist' %}</h1>
      <div class="row">

        {% for product in wishlist %}
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="card">
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.get_image }}" class="card-img-top" alt="Product image" style="height: 300px; object-fit: cover;" />
              </a>
              <div class="card-body">
                <div class="d-flex justify-content-between">
                  <p class="small"><a href="#!" class="text-muted h6">{% trans 'Category' %}: {{ product.category }}</a></p>
                  {% if product.discount_price %}
                  <p class="small text-danger"><s>
                    {{product.price}} zl
                  </s></p>
                  {% endif %}
                </div>
    
                <div class="d-flex justify-content-between mb-3">
                  <a href="{{ product.get_absolute_url }}"><h5 class="mb-0 text-dark">{{ product.title }}</h5></a>
                  <h5 class="text-dark mb-0">
                    {% if product.discount_price %}
                      {{ product.discount_price }} zl
                    {% else %}
                      {{ product.price }} zl
                    {% endif %}
                  </h5>
                </div>
    
                <div class="d-flex justify-content-between mb-2">
                  <p class="text-muted mb-0">{% trans 'By' %}: <span class="fw-bold h6">{{ product.user.fullname }}</span></p>
                  <div class="ms-auto text-warning">
                  </div>
                </div>
                <div class="card-footer d-flex justify-content-around gap-2 mb-0 me-0 pb-0 px-0">
                  <a href="{% url 'users:remove_from_wishlist' product.id %}" class="btn btn-danger w-50 btn-lg active px-1" role="button" aria-pressed="true" title="Remove from wishlsit">
                    <font class="h6">{% trans 'Remove from wishlist' %}</i></font>
                  </a>
                </div>
              </div>
            </div>
          </div>
        {% empty %}
        <div class="col-md-12 col-lg-12 mb-4 mb-lg-0 d-flex justify-content-center py-3">
          <div class="card py-5 w-50 text-center">
            <h3 class="text-info py-1">{% trans 'Nothing here yet' %} :)</h3>
            <a href="{% url 'products:home' %}" class="h4  py-2 link text-primary text-decoration-underline">{% trans 'Go Shopping' %}</a>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </section>
{% endblock %}