src/api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.ProductList.as_view(), name='product_list'),
    path('products/<slug:pk>', views.ProductDetail.as_view(), name='product_detail'),

    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
]

src/core/apps/products/urls.py
from django.urls import path

from . import views


app_name = 'products'

urlpatterns = [
    path('', views.product_all, name='home'),

    path('add', views.product_add, name='add'),
    path('<slug:pk>', views.product_detail, name='detail'),
    path('<slug:pk>/edit', views.product_edit, name='edit'),
    path('<slug:pk>/edit/remove-image', views.remove_image, name='remove_image'),
    path('<slug:pk>/remove', views.product_remove, name='remove'),

    path('category/<slug:category_name>', views.category, name='category'),
]

src/core/apps/search/urls.py
from django.urls import path

from . import views


app_name = 'search'

urlpatterns = [
    path('', views.main, name='main')
]

src/core/apps/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate-user/<uidb64>/<token>', views.activate_user, name='activate'),
    path('resend-activation-email/<slug:user_id>', views.resend_activation_email, name='resend_activation'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/upvote', views.upvote_feedback, name='upvote_feedback'),
    path('feedback/delete', views.delete_feedback, name='delete_feedback'),

    path('<int:pk>', views.user_profile, name='profile'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('edit-profile/remove-image', views.remove_image, name='remove_image'),

    path('change-password/', views.change_password, name='change_password'),
    path('change-to-new-password/<uidb64>/<uidb64_2>/<token>', views.change_to_new_password, name='confirm_new_password'),

    path('my-wishlist/', views.wishlist, name='wishlist'),
    path('add-to-wishlist/<slug:product_id>', views.add_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<slug:product_id>', views.remove_from_wishlist, name='remove_from_wishlist'),
    
    path('<int:user_reported_id>/report', views.report_user, name='report'),
    path('<slug:user_reported_id>_<slug:message_id>/report', views.report_user, name='report'),

    path('blocked_users/', views.blocked_users, name='blocked'),
    path('blocked_users/remove/<int:user_id>', views.unblock_user, name='unblock'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.static import serve

from core.apps.products.views import product_all
from core.apps.users.views import about_page

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('api/auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
]

urlpatterns += i18n_patterns(
    path('', product_all, name='home'),
    path('about/', about_page, name='about_page'),
    path('products/', include('core.apps.products.urls', namespace='products')),
    path('users/', include('core.apps.users.urls', namespace='users')),
    path('chats/', include('core.apps.chats.urls', namespace='chats')),
    path('search/', include('core.apps.search.urls', namespace='search')),
    prefix_default_language=False
)

handler404 = 'core.views.custom_handler404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = [
        *urlpatterns,
        path('__debug__/', include('debug_toolbar.urls'))
    ]
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

src/core/apps/products/models.py
import uuid
import json

from django.conf import settings
from django.db import models
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from django.db.models.signals import (
    post_save,
    post_delete
)
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from core.apps.users.models import UserAccount
from core.utils import (
    get_fixtures_directory,
    create_or_update_fixture_signal,
    delete_fixture_signal
)


fixtures_directory = get_fixtures_directory()


class ActiveProductsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(purchased_by=None)


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(verbose_name=_('title'), max_length=40, db_index=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='products', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', related_name='products', on_delete=models.PROTECT, default=1)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    discount_price = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    description = models.CharField(verbose_name=_('description'), max_length=300, blank=True)
    if settings.DEBUG:
        image = models.ImageField(
            verbose_name=_("image"),
            help_text=_("Upload an image"),
            upload_to="images/products",
            default="../static/images/blank.jpg"
        )
    else:
        image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload an image"),
        upload_to="images/products",
        default=None,
        null=True, blank=True)
    tags = models.ManyToManyField('Tag', related_name='products', blank=True)
    pub_date = models.DateTimeField(verbose_name=_('publication date'), auto_now_add=True, editable=False)
    purchased_by = models.ForeignKey(UserAccount, related_name='purchased_products', on_delete=models.CASCADE, null=True, blank=True)

    objects = models.Manager()
    active_products = ActiveProductsManager()

    class Meta:
        ordering = ['-pub_date']

    @property
    def get_image(self):
        if not settings.DEBUG and not self.image:
            return 'https://sellorbucket.s3.amazonaws.com/static/images/blank.jpg'
        return self.image.url

    @property
    def is_active(self):
        if self.purchased_by == None:
            return True
        return False

    @property
    def discount_percentage(self):
        discount_in_percent = 100 - (self.discount_price * 100 / self.price)
        return "%.1f" % discount_in_percent
    
    @property
    def current_price(self):
        if self.discount_price:
            return self.discount_price
        return self.price

    def __str__(self) -> str:
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('products:detail', args=[self.id])

    def save(self, *args, **kwargs) -> None:
        self.title: str = self.title.capitalize()
        if self.description:
            self.description: str = self.description.title()
        if self.discount_price:
            if self.discount_price >= self.price:
                raise ValueError(_('Discount price cannot be higher than regular.'))
        return super().save(*args, **kwargs)

@receiver(post_save, sender=Product)
def product_created_handler(sender, instance, created, *args, **kwargs):
    if instance.purchased_by != None:
        instance.wishlists.clear()


class Category(models.Model):
    name = models.CharField(verbose_name=_('category name'), max_length=50, unique=True)
    slug = models.SlugField(unique=True, help_text='no polish special chars allowed')

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self) -> str:
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('products:category', args=[self.slug])


categories_fixture_file_dir = fixtures_directory + '/categories_fixture.json'

@receiver(post_save, sender=Category)
def category_created_handler(sender, instance, created, *args, **kwargs):
    create_or_update_fixture_signal(sender, instance, created, raw=kwargs.pop('raw'), \
        fixture_file_dir=categories_fixture_file_dir, fields=('name', 'slug', 'name_pl'), *args, **kwargs)

@receiver(post_delete, sender=Category)
def category_deleted_handler(sender, instance, *args, **kwargs):
    delete_fixture_signal(sender, instance, fixture_file_dir=categories_fixture_file_dir, *args, **kwargs)


class Tag(models.Model):
    name = models.CharField(verbose_name=_('tag name'), max_length=50, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return f'{self.name}'

tags_fixture_file_dir = fixtures_directory + '/tags_fixture.json'

@receiver(post_save, sender=Tag)
def tag_created_handler(sender, instance, created, *args, **kwargs):
    create_or_update_fixture_signal(sender, instance, created, raw=kwargs.pop('raw'), \
        fixture_file_dir=tags_fixture_file_dir, fields=('name',), *args, **kwargs)

@receiver(post_delete, sender=Tag)
def tag_deleted_handler(sender, instance, *args, **kwargs):
    delete_fixture_signal(sender, instance, fixture_file_dir=tags_fixture_file_dir, *args, **kwargs)

src/core/apps/products/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


from .models import Product, Category, Tag

class ProductForm(forms.ModelForm):
    title = forms.CharField(max_length=50)
    image = forms.FileField(label=_('Product picture'), widget=forms.FileInput(), required=False)
    category = forms.ModelChoiceField(widget=forms.Select(), queryset=Category.objects.all(), required=True)
    description = forms.CharField(label=_('Description'), max_length=300, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '4'}), required=False)
    tags = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(attrs={'class': 'form-control'}), queryset=Tag.objects.all(), required=False)

    def __init__(self, *args, **kwargs) -> None:
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'form-control form-control-lg'
        self.fields['category'].widget.attrs['class'] = 'form-select'
        self.fields['price'].widget.attrs['class'] = 'form-control'
        self.fields['discount_price'].widget.attrs['class'] = 'form-control'
        self.fields['tags'].widget.attrs['style'] = 'height: 170px;'
        self.fields['image'].widget.attrs['id'] ='productImageInput'
        self.fields['image'].widget.attrs['accept'] ='.jpg,.jpeg,.png'
        self.fields['image'].widget.attrs['onchange'] ='readURL(this); validateFileType()'

    class Meta:
        model = Product
        fields = ['title', 'category', 'price', 'discount_price', 'description', 'tags', 'image']

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title').capitalize()
        if Product.objects.filter(user=self.user, purchased_by=None).exclude(id=self.instance.id).filter(title=title).exists():
            self.add_error('title', _('You already have product with given title, please rename product.'))
        discount_p = cleaned_data.get('discount_price')
        if discount_p and discount_p >= cleaned_data.get('price'):
            self.add_error('discount_price', _('Discount price cannot be higher or same as regular.'))
        return cleaned_data

src/core/apps/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponseForbidden
from django.utils.translation import gettext_lazy as _

from core.utils import previous_url_or_other, available_products
from core.apps.users.models import Visitor
from .models import Product, Category, Tag
from .forms import ProductForm


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def category(request, category_name):
    category = get_object_or_404(Category, slug=category_name)
    products = available_products(request, Product.active_products.filter(category=category))
    product_paginator = Paginator(products, 10)
    products_page = product_paginator.get_page(request.GET.get('page'))
    context = {'category_name': category.name, 'page_obj': products_page}
    return render(request, 'products/category.html', context)


def product_all(request):
    ip_addr = get_client_ip(request)
    visitor, created = Visitor.objects.get_or_create(ip=ip_addr)
    products = available_products(request, Product.active_products).select_related('user')
    paginator = Paginator(products, 10)
    products_page = paginator.get_page(request.GET.get('page'))
    context = {'page_obj': products_page}
    return render(request, 'products/home.html', context)


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk, purchased_by=None)
    if request.user.is_authenticated:
        if product.user in request.user.blacklist.blocked_users.all() or request.user in product.user.blacklist.blocked_users.all():
            messages.warning(request, _('This product is not available.'))
            return previous_url_or_other(request, reverse('products:home'))
    context = {'product': product}
    return render(request, 'products/product_detail.html', context)


@login_required
def product_add(request):
    if request.method == 'POST':
        create_form = ProductForm(request.POST, request.FILES, user=request.user)
        if create_form.is_valid():
            new_product = create_form.save(commit=False)
            new_product.user = request.user
            new_product.save()
            new_product.tags.add(*create_form.cleaned_data.get('tags'))
            messages.success(request, _('Product succesfully created.'))
            return redirect('products:detail', new_product.id)
    else:
        create_form = ProductForm()
    context = {'form': create_form}
    return render(request, 'products/product_create.html', context)


@login_required
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk, purchased_by=None)
    if product.user != request.user:
        return HttpResponseForbidden('You don\'t have permission to access this resource')
    if request.method == 'POST':
        edit_form = ProductForm(request.POST, request.FILES, instance=product, user=request.user)
        if edit_form.is_valid():
            product = edit_form.save()
            messages.success(request, _('Product succesfully updated. ') + f'<a href="{product.get_absolute_url()}" class="text-decoration-underline">' + _('See') + '</a>')
    else:
        edit_form = ProductForm(instance=product)
    context = {'form': edit_form, 'product': product}
    return render(request, 'products/product_edit.html', context)
    

@login_required
def remove_image(request, pk):
    product = get_object_or_404(Product, pk=pk, user=request.user.id, purchased_by=None)
    product.image = '../static/images/blank.jpg'
    product.save()
    messages.success(request, _('Image deleted.'))
    return redirect('products:edit', pk)


@login_required
def product_remove(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.user != product.user:
        return HttpResponseForbidden('You don\'t have permission to access this resource')
    if request.method == 'POST':
        product.delete()
        messages.success(request, _('Product removed.'))
        return redirect('products:home')
    context = {'product': product}
    return render(request, 'products/product_remove_confirm.html', context)

src/templates/products/category.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}
{% load i18n %}

{% block content %}
  <style>
    ul, li {
        list-style: none;
    }
  </style>

  <section class="bg-dark">
    <div class="container py-4">

      <h1 class="text-center text-light">{{ category_name|title }}</h1>

      <div class="row justify-content-center mb-3 gap-3">
        <hr>
        {% for product in page_obj %}
          {% include 'products/product_card.html' %}
        {% empty %}
          <h2 class="text-light text-center">{% trans 'Nothing found :(' %}</h2>
        {% endfor %}

      </div>

      {% if is_paginated %}
        {% include 'pagination_nav.html' %}
      {% endif %}

    </div>
  </section>
{% endblock %}

src/templates/products/home.html
{% extends 'base.html' %}
{% load my_tags %}
{% load i18n %}
{% load static %}

{% block content %}
<section class="bg-dark">
  {% if not request.user.is_authenticated %}
  <div class="p-5 text-center bg-image"
    style="background-image: url({% static 'images/main-background.jpg' %});
    height: 455px;">
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="container w-75 text-white">
          <h1 class="mb-3">
            Sellor
          </h1>
          <h4 class="mb-3">{% trans 'We are a very powerful and safe platform with million users around the Poland where you can buy or sell anything you want.' %}</h4>
          <h5 class="mb-4">{% trans 'Start journey by creating an account/Loggining In' %}</h5>
          <a class="btn btn-light btn-lg me-1 px-4" href="{% url 'users:register' %}" role="button"
          >{% trans 'Register' %}</a
          >
          <a class="btn btn-light btn-lg ms-1 px-4" href="{% url 'users:login' %}" role="button"
          >{% trans 'Log In' %}</a
          >
        </div>
      </div>
    </div>
  </div>
  {% endif %}


  <div class="container py-3">
    <div class="row justify-content-center mb-3 g-4">

      {% for product in page_obj %}
        {% include 'products/product_card.html' %}
        {% empty %}
        <h2 class="text-center text-light pt-2 pb-1">{% trans 'No products yet :(' %}</h2>
        <a href="{% url 'products:add' %}" class="h3 text-center text-decoration-underline text-info pb-2">{% trans 'Add new!' %}</a>
      {% endfor %}

      {% if is_paginated %}
        {% include 'pagination_nav.html' %}
      {% endif %}

    </div>
  </div>
</section>
{% endblock %}

src/templates/products/product_card.html
{% load my_tags %}
{% load static %}
{% load i18n %}

<style>
  .btn {
    font-size: 0.9rem;
  }
</style>

<div class="col-md-12 col-xl-10">
  <div class="card shadow-0 border rounded-3">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0 text-center">
          <div class="bg-image hover-zoom ripple rounded ripple-surface">
            <img src="{{ product.get_image }}" style="height: 220px; object-fit: cover;" class="w-100" />
            <a href="{{ product.get_absolute_url }}">
              <div class="hover-overlay">
                <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-6 col-xl-6">
          <div class="d-flex justify-content-between pb-1 mb-2" style="border-bottom: 2px solid lightgray">
            <div class="">
              <h3>
                <a href="{{ product.get_absolute_url }}" class="text-dark">{{ product.title|truncatechars:20|title }}</a>
              </h3>
              <h6>
                <form action="{% url 'search:main' %}" method="get">
                  <input type="hidden" name="location" value="{{ product.user.location.id }}">
                  <input type="submit" value="{{ product.user.location }}" class="btn btn-outline-primary text-dark">
                </form>
              </h6>
              <div class="h5 btn btn-info text-light">
                <a href="{{ product.category.get_absolute_url }}">{% trans 'Category' %}: {{ product.category }}</a>
              </div>
            </div>
            <a href="{{ product.user.get_absolute_url }}">
              <div class="author text-end">
                <img src="{{ product.user.get_image }}" alt="" style="object-fit: cover; width: 65px; height: 65px"
                  class="rounded-circle" />
                <div class="author-name mt-1 d-flex justify-content-center text-end" style="font-size: 0.9rem;">
                  <span href="{{ product.user.get_absolute_url }}"
                    class="fw-bold h6">{{ product.user.fullname }}</span>
                </div>
              </div>
            </a>
          </div>
          {% if product.tags.all %}
          <div class="mb-0 text-muted btn btn-dark">
            <div class="h6 text-light">{% trans 'Tags' %}:
              {% for tag in product.tags.all %}
                {% if forloop.counter != 1 %}
                <span class="text-primary text-light"> • </span>
                {% endif %}
                <span class="text-light" style="font-size: 0.75rem;">{{ tag }}</span>
              {% endfor %}
            </div>
          </div>
          {% endif %}

          <p class="mt-2 mb-md-0">
            {% if product.description %}
            <span class="text-muted text-decoration-underline">{% trans 'Description' %}:</span>
            {{ product.description|truncatechars:80 }}
            {% endif %}
          </p>
        </div>
        <div
          class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start d-flex flex-column justify-content-between">
          <div class="d-flex flex-row align-items-center justify-content-center mb-1 h-100">
            {% if product.discount_price %}
            <span class="mb-1 me-1 h4">{{ product.discount_price }} zł</sp>
              <span class="text-danger h5"><s>{{ product.price }} zł</s></span>
              {% else %}
              <h4 class="mb-1 me-1 h4">{{ product.price }} zł</h4>
              {% endif %}
          </div>

          <div class="d-flex flex-column gap-1">
            <a href="{% url 'products:detail' product.id %}" class="btn btn-primary btn-sm py-3"
              type="button">{% trans 'Details' %}</a>
            {% if request.user == product.user %}
            <a href="{% url 'products:edit' product.id %}" class="btn btn-warning btn-sm py-3" type="button">{% trans 'Edit' %}</a>
            <a href="{% url 'products:remove' product.id %}" class="btn btn-danger btn-sm py-3" type="button">
              {% trans 'Remove from Site' %}
            </a>
            {% else %}
            {% if product in request.user.wishlist.all %}
            <a href="{% url 'users:remove_from_wishlist' product.id %}" class="btn btn-danger btn-sm py-2"
              type="button">
              {% trans 'Remove from Wishlist' %}
            </a>
            {% else %}
            <a href="{% url 'users:add_to_wishlist' product.id %}" class="btn btn-secondary btn-sm py-3" type="button">
              {% trans 'Add to wishlist' %}
            </a>
            {% endif %}
            <a href="{% url 'chats:detail' product.id %}" class="btn btn-success btn-sm py-3 fw-bold" type="button">
              {% trans 'Buy / Negotiate' %}
            </a>
            {% endif %}

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/products/product_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% load i18n %}

{% block content %}
<section class="bg-dark">
  <div class="container py-3">
      <div class="card">
          <div class="card-body">
              <div class="row py-3">
                  <div class="col-lg-4 col-md-12 col-sm-12 mb-3">
                      <div class="white-box text-center"><img src="{{ product.get_image }}" style="width: 85%; object-fit: cover; border: 2px solid black; border-radius: 5px;" class="img-responsive"></div>
                  </div>
                  <div class="col-lg-5 col-md-7 col-sm-7 text-center text-md-start">
                    <div class="">
                      <h3><a href="{{ product.get_absolute_url }}" class="text-dark">{{ product.title|title }}</a></h3>
                      <h6>
                        <form action="{% url 'search:main' %}" method="get">
                          <input type="hidden" name="location" value="{{ product.user.location.id }}">
                          <input type="submit" value="{{ product.user.location }}" class="btn btn-outline-primary text-dark" style="font-size: 0.9rem;">
                        </form>
                      </h6>
                      <div class="h5 btn btn-info text-light p-2">
                        <a href="{{ product.category.get_absolute_url }}" class="h6">{% trans 'Category' %}: {{ product.category }}</a>
                      </div>
                    </div>
                    {% if product.tags.all %}
                      <div class="mb-0 text-muted btn btn-dark">
                        <div class="h6 text-light">{% trans 'Tags' %}: </div>
                        {% for tag in product.tags.all %}
                          {% if forloop.counter != 1 %}
                          <span class="text-primary text-light"> • </span>
                          {% endif %}
                          <span class="text-light">{{ tag }}</span>
                        {% endfor %}
                      </div>
                    {% endif %}
                    <hr>
                    {% if product.description %}
                    <h3 class="h4 mt-3">{% trans 'Description' %}:</h3>
                      <p>{{ product.description|truncatechars:120 }}</p>
                    {% endif %}
                  </div>
                  <div class="col-lg-3 col-md-5 col-sm-5 text-center">
                    <div class="w-100 btn btn-dark py-4 px-3">
                      {% if product.discount_price %}
                        <div class="">
                          <h3 class="h3">{{ product.discount_price }} zł</h3>
                          <span class="text-danger h5"><s>{{ product.price }} zł</s></span>
                        </div>
                        <div class="">
                          <small class="text-success h6" style="font-size:1.2rem">({{ product.discount_percentage }}% off)</small>
                        </div>
                      {% else %}
                      <div class="h3">
                        {{ product.price }} zł.
                      </div>
                      {% endif %}
                      <div class="author mt-5">
                        <a href="{{ product.user.get_absolute_url }}">
                          <div class="mb-1">
                            <span class="h5" style="font-size: 1.3rem">{{ product.user.fullname }}</span>
                          </div>
                          <div class="">
                            <img src="{{ product.user.get_image }}" alt="" style="object-fit: cover; width: 95px; height: 95px"
                            class="rounded-circle img-fluid img-thumbnail"/>
                          </div>
                        </a>
                      </div>
                    </div>
                </div>
              </div>
              <div class="row mt-2 flex-column align-items-center">
                {% if request.user == product.user %}
                  <a href="{% url 'products:edit' product.id %}" class="btn btn-secondary btn-rounded mr-1 px-5 mb-2 py-3 w-50" type="button">
                    <font class="h5">{% trans 'Edit' %} <i class="fa-solid fa-marker ms-1"></i></font>
                  </a>
                  <a href="{% url 'products:remove' product.id %}" class="btn btn-danger btn-rounded px-4 py-3 w-50" type="button">
                    <font class="h5">{% trans 'Remove from Site' %} <i class="fa-solid fa-trash-can ms-1"></i></font>
                  </a>
                {% else %}
                  <a href="{% url 'chats:detail' product.id %}" class="btn btn-success btn-rounded px-4 py-3 w-50 mb-2">
                    <font class="h5">{% trans 'Buy / Negotiate' %} &nbsp;<i class="fa-solid fa-comments"></i></font>
                  </a>
                  {% if product in request.user.wishlist.all %}
                  <a href="{% url 'users:remove_from_wishlist' product.id %}" class="btn btn-danger btn-rounded px-4 py-3 w-50">
                    <font class="h5">{% trans 'Remove from wishlist' %} &nbsp;<i class="fa-solid fa-bookmark"></i></font>
                  </a>
                  {% else %}
                  <a href="{% url 'users:add_to_wishlist' product.id %}" class="btn btn-primary btn-rounded px-4 py-3 w-50">
                    <font class="h5">{% trans 'To wishlist' %} &nbsp;<i class="fa-solid fa-bookmark"></i></font>
                  </a>
                  {% endif %}
                {% endif %}
              </div>
          </div>
      </div>
  </div>
</section>
{% endblock %}

src/templates/products/product_remove_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<section class="h-100 bg-dark">
  <div class="container py-3 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0 justify-content-center">
            <div class="col-md-8 col-lg-8 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form action="" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">{% trans 'Are You sure you want to delete' %} <a href="{{ product.get_absolute_url }}"><i>{{ product.title }}?</i></a></span>
                  </div>

                  <div class="mt-5 mb-3">
                    <button class="btn btn-danger btn-lg btn-block" type="submit"><span class="h4">{% trans 'Confirm' %}</span></button>
                    <div class="pt-5">
                      <h6 class="mb-0"><a href="{% url 'products:home' %}" class="text-body h5"><i
                            class="fas fa-long-arrow-alt-left me-2"></i>{% trans 'No, Back to shop' %}</a></h6>
                    </div>
                  </div>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}