src/api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.ProductList.as_view(), name='product_list'),
    path('products/<slug:pk>', views.ProductDetail.as_view(), name='product_detail'),

    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
]

src/core/apps/chats/urls.py
from django.urls import path

from . import views


app_name = 'chats'

urlpatterns = [
    path('', views.chats_all, name='all'),
    path('<slug:product_id>_<slug:chat_id>/', views.enter_chat, name='detail'),
    path('<slug:product_id>/', views.enter_chat, name='detail'),
    path('<slug:chat_id>/delete', views.delete_chat, name='delete'),
    path('<slug:chat_id>/request-done-deal', views.request_done_deal, name='request_done_deal'),
    path('<slug:chat_id>/request-done-deal-cancel', views.request_done_deal_cancel, name='request_done_deal_cancel'),
    path('<slug:chat_id>/confirm-deal', views.confirm_deal, name='confirm_deal'),
    path('<slug:message_id>/read', views.read_message, name='read_message'),

    path('check-for-messages', views.check_for_new_messages, name='check_for_new_messages'),
    path('check-for-done-deal-request/<slug:chat_id>', views.check_for_done_deal_request, name='check_for_done_deal_request'),
    path('check-for-confirm-deal/<int:customer_id>', views.check_for_confirm_deal, name='check_for_confirm_deal'),
]

src/core/apps/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate-user/<uidb64>/<token>', views.activate_user, name='activate'),
    path('resend-activation-email/<slug:user_id>', views.resend_activation_email, name='resend_activation'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/upvote', views.upvote_feedback, name='upvote_feedback'),
    path('feedback/delete', views.delete_feedback, name='delete_feedback'),

    path('<int:pk>', views.user_profile, name='profile'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('edit-profile/remove-image', views.remove_image, name='remove_image'),

    path('change-password/', views.change_password, name='change_password'),
    path('change-to-new-password/<uidb64>/<uidb64_2>/<token>', views.change_to_new_password, name='confirm_new_password'),

    path('my-wishlist/', views.wishlist, name='wishlist'),
    path('add-to-wishlist/<slug:product_id>', views.add_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<slug:product_id>', views.remove_from_wishlist, name='remove_from_wishlist'),
    
    path('<int:user_reported_id>/report', views.report_user, name='report'),
    path('<slug:user_reported_id>_<slug:message_id>/report', views.report_user, name='report'),

    path('blocked_users/', views.blocked_users, name='blocked'),
    path('blocked_users/remove/<int:user_id>', views.unblock_user, name='unblock'),
]

src/core/apps/chats/models.py
import uuid
import datetime

from django.db import models
from django.utils import timezone, dateformat

from core.apps.users.models import UserAccount
from core.apps.products.models import Product
from django.db.models import Q


class Chat(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    product = models.ForeignKey(Product, related_name='chats', on_delete=models.CASCADE, null=True)
    seller = models.ForeignKey(UserAccount, related_name='seller_chats', on_delete=models.CASCADE, null=True)
    customer = models.ForeignKey(UserAccount, related_name='customer_chats', on_delete=models.CASCADE, null=True)
    started_at = models.DateTimeField(default=timezone.now, editable=False)
    done_deal_requested = models.BooleanField(default=False)

    @property
    def sellers_unseen_messages_count(self) -> int:
        return int(self.messages.filter(Q(is_seen=False) & (Q(author=self.customer) | Q(is_system_generated=True))).count())

    @property
    def customers_unseen_messages_count(self) -> int:
        return int(self.messages.filter(Q(is_seen=False) & (Q(author=self.seller) | Q(is_system_generated=True))).count())

    @property
    def participants(self) -> list:
        return [self.seller, self.customer]

    @property
    def last_30_messages(self):
        return reversed(self.messages.order_by('-sent_at')[:30])
    
    @property
    def get_last_message(self) -> object:
        if self.messages.last():
            return self.messages.last()
        return None

    @property
    def last_message_text(self) -> str:
        last_msg = self.get_last_message.text or ''
        if len(last_msg) > 40:
            return last_msg[0:40] + '...'
        return last_msg
    
    @property
    def last_message_date(self) -> str:
        if self.get_last_message:
            return self.get_last_message.sent_date
        return ''
    
    def __str__(self) -> str:
        return f'Chat {self.seller.email}, {self.customer.email} of {self.product.title}'


class Message(models.Model):
    author = models.ForeignKey(UserAccount, related_name='messages', on_delete=models.CASCADE, null=True)
    chat = models.ForeignKey(Chat, related_name='messages', on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    sent_at = models.DateTimeField(default=timezone.now, editable=False)
    is_system_generated = models.BooleanField(default=False)
    is_seen = models.BooleanField(default=False)

    @property
    def sent_date(self):
        current_date = str(datetime.datetime.now().date())
        date_sent = dateformat.format(self.sent_at, "Y-m-d")    
        if current_date == date_sent:
            return dateformat.format(self.sent_at, "H:i")

        current_year = str(datetime.datetime.now().year)
        year_sent = dateformat.format(self.sent_at, "Y")
        if year_sent == current_year:
            return dateformat.format(self.sent_at, "H:i d.m")
        return dateformat.format(self.sent_at, "H:i d.m.y")

    def __str__(self) -> str:
        if not self.is_system_generated:
            return f'Message by {self.author.email} at {dateformat.format(self.sent_at, "d.m.y, H:i:s")}'
        return f'System-generated message at {dateformat.format(self.sent_at, "d.m.y, H:i:s")}'

src/core/apps/chats/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponseForbidden
from django.utils.translation import gettext_lazy as _

from core.apps.products.models import Product
from core.apps.users.models import UserAccount
from .models import Chat, Message


@login_required
def chats_all(request):
    seller_chats = Chat.objects.filter(seller=request.user)
    seller_chats = sorted(seller_chats, key=lambda chat: (chat.get_last_message.sent_at, chat.done_deal_requested))
    seller_chats.reverse()
    customer_chats = Chat.objects.filter(customer=request.user)
    customer_chats = sorted(customer_chats, key=lambda chat: (chat.get_last_message.sent_at, chat.done_deal_requested))
    customer_chats.reverse()
    context = {'seller_chats': seller_chats, 'customer_chats': customer_chats}
    return render(request, 'chats/all_chats.html', context)


@login_required
def enter_chat(request, product_id, chat_id=None):
    user = request.user
    context = {'chatting_with_id': ''}
    if chat_id:
        chat = get_object_or_404(Chat, id=chat_id)
        if user == chat.seller:
            context['chatting_with_id'] = chat.customer.id
        elif user == chat.customer:
            context['chatting_with_id'] = chat.seller.id
        else:
            return HttpResponseForbidden('You don\'t have permission to access this resource')

    else:
        product = get_object_or_404(Product, id=product_id)
        seller = product.user
        if user == seller: 
            return redirect('products:detail', product.id)
        # user is customer starting or entering a chat
        # validate if user is blocked by seller or has blocked seller
        if user.is_blocked_by(seller):
            messages.warning(request, _('You cannot start conversation with this user.'))
            return redirect('products:home')
        if user.has_blocked(seller):
            messages.warning(request, _('You blocked this user.'))
            return redirect('users:blocked')
        chat, created = Chat.objects.get_or_create(product=product, seller=seller, customer=user)
        if created:
            message = Message.objects.create(is_system_generated=True, chat=chat, text='Chat created. Customer now should start conversation.', author=None, is_seen=False)
            message.save()
        context['chatting_with_id'] = chat.seller.id

    chat.messages.exclude(author=request.user).update(is_seen=True)
    context['chat'] = chat
    return render(request, 'chats/detail_chat.html', context)


@login_required
def delete_chat(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    if request.user not in [chat.seller, chat.customer]:
        return redirect('products:detail', chat.product.id)
    chat.delete()
    messages.success(request, _('Chat deleted.'))
    return redirect('chats:all')


@login_required
def read_message(request, message_id):
    message = get_object_or_404(Message, id=message_id)
    if request.user not in message.chat.participants or request.user == message.author:
        return HttpResponseForbidden('You don\'t have permission to access this resource')
    message.is_seen = True
    message.save()
    return JsonResponse({'success': True})


@login_required
def request_done_deal(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    if request.user == chat.seller:
        if not chat.done_deal_requested == True:
            chat.done_deal_requested = True
            Message.objects.create(
                chat=chat, is_system_generated=True,
                text='Seller marked this deal as done, if it\'s true customer should confirm it by clicking button on the panel', author=None)
            chat.save()
        return redirect('chats:detail', chat.product.id, chat_id)
    return HttpResponseForbidden('You don\'t have permission to access this resource')


@login_required
def request_done_deal_cancel(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    if request.user == chat.seller:
        chat.done_deal_requested = False
        Message.objects.filter(
            chat=chat, is_system_generated=True,
            text='Seller marked this deal as done, if it\'s true customer should confirm it by clicking button on the panel', author=None).delete()
        chat.save()
        return redirect('chats:detail', chat.product.id, chat_id)
    return HttpResponseForbidden('You don\'t have permission to access this resource')


@login_required
def confirm_deal(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    if request.user == chat.customer and chat.done_deal_requested == True:
        chat.product.purchased_by = request.user
        chat.product.save()
        chat.delete()
        messages.success(request, _('We\'re happy you completed a purchase via our website!'))
        return redirect('users:dashboard')
    return HttpResponseForbidden('You don\'t have permission to access this resource')


@login_required
def check_for_new_messages(request):
    return JsonResponse({'newMessagesCount': request.user.unseen_messages_count})


@login_required
def check_for_done_deal_request(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id, customer=request.user)
    return JsonResponse({'is_requested': chat.done_deal_requested})


@login_required
def check_for_confirm_deal(request, customer_id):
    customer = get_object_or_404(UserAccount, pk=customer_id)
    if request.user.products.filter(purchased_by=customer).exists():
        return JsonResponse({'is_confirmed': 'true'})
    return JsonResponse({'is_confirmed': 'false'})

src/templates/chats/detail_chat.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}
{% load i18n %}

{% block extrahead %}
<style>
  body {
    min-height: 100vh;
  }

  p {
    word-break: break-all;
    white-space: normal;
  }

  ::-webkit-scrollbar {
    width: 10px;
  }

  ::-webkit-scrollbar-track {
    width: 5px;
    background: #f5f5f5;
  }

  ::-webkit-scrollbar-thumb {
    width: 1em;
    background-color: #ddd;
    outline: 1px solid slategrey;
    border-radius: 1rem;
  }

  .text-small {
    font-size: 0.8rem;
  }

  .chat-box {
    height: 510px;
    overflow-y: scroll;
  }

  .message-time {
    font-size: 0.75rem !important;
  }

  input::placeholder {
    font-size: 0.9rem;
    color: #999;
  }

  @media only screen and (max-width: 800px) {
    .chat-box {
      height: 460px;
    }
  }
</style>
{% endblock extrahead %}


{% block content %}
<div class="container pt-3">
  <div class="row gap-md-0 gap-sm-4">
    <!-- User Info -->
    <div class="col-12 col-md-3">
      <div class="btn btn-dark border border-3 d-flex flex-column justify-content-between px-1">
        <div class="product">
          <h5 class="py-1">{% if request.user == chat.customer %}{% trans 'YOU WANT TO BUY' %}{%else%}{% trans 'YOU SELL' %}{%endif%}</h5>
          <a href="{{ chat.product.get_absolute_url }}">
            <div class="mb-3">
              <img src="{{ chat.product.get_image }}" alt="" style="object-fit: cover; width: 105px; height: 105px"
                class="rounded-circle img-fluid img-thumbnail" />
            </div>
            <div class="btn btn-primary">
              <span class="h5">{{ chat.product.title }}</span> {% trans 'for' %}
              <span class="text-decoration-underline" style="font-size: 1.2rem;">{{ chat.product.current_price }}
                zł.</span>
            </div>
          </a>
        </div>
        <div class="author mt-5">
          {% if request.user == chat.customer %}
          <h5 class="py-1">{% trans 'FROM' %}</h5>
          <a href="{{ chat.seller.get_absolute_url }}">
            <div class="mb-3">
              <img src="{{ chat.seller.get_image }}" alt="" style="object-fit: cover; width: 105px; height: 105px"
                class="rounded-circle img-fluid img-thumbnail" />
            </div>
            <div class="btn btn-primary">
              <div class="h5 my-auto" style="font-size: 1rem">{{ chat.seller.fullname }}</div>
              <div class="h5 my-auto" style="font-size: 1rem">({{ chat.seller.location }})</div>
            </div>
          </a>
          {% else %}
          <h5 class="py-1">TO</h5>
          <a href="{{ chat.customer.get_absolute_url }}">
            <div class="mb-3">
              <img src="{{ chat.customer.get_image }}" alt="" style="object-fit: cover; width: 105px; height: 105px"
                class="rounded-circle img-fluid img-thumbnail" />
            </div>
            <div class="btn btn-primary mx-auto">
              <div class="h5" style="font-size: 1rem">{{ chat.customer.fullname }}</div>
              <div class="h5 my-auto" style="font-size: 1rem">({{ chat.customer.location }})</div>
            </div>
          </a>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Chat Box-->
    <div class="col-12 col-md-7">
      <div id="messages-list" class="px-2 py-1 chat-box bg-white">

        {% for message in chat.last_30_messages %}
        {% if message.is_system_generated %}
        <div class="media mx-auto w-50 mb-4 text-center">
          <div class="media-body">
            <div class="bg-secondary rounded py-3 px-3 mb-1">
              <p class="mb-0 text-white h6" style="word-break: normal;">{{ message.text }}</p>
            </div>
            <p class="message-time small text-muted text-center">
              {{ message.sent_date }}
            </p>
          </div>
        </div>
        {% else %}
        {% if message.author == request.user %}
        <div class="media w-50 ms-auto mb-3">
          <div class="media-body">
            <div class="bg-primary rounded py-2 px-3 mb-1">
              <p class="text-small mb-0 text-white">{{ message.text }}</p>
            </div>
            <p class="message-time small text-muted text-end">
              {% trans 'You at' %}
              {{ message.sent_date }}
            </p>
          </div>
        </div>
        {% else %}
        <div class="media w-50 mb-3">
          <div class="media-body ms-1">
            <div class="bg-info rounded py-2 px-3 mb-1 d-flex justify-content-between">
              <p class="text-small mb-0 text-light">{{ message.text }}</p>
              <a href="{% url 'users:report' chatting_with_id message.id %}">
                <small class="text-danger" title="{% trans 'Report User' %}">
                  <i class="fa-solid fa-hand">!</i>
                </small>
              </a>
            </div>
          </div>
          <div class="message-bottom">
            <p class="message-time small text-muted ms-2">
              {{ message.author.first_name }}
              {% trans 'at' %} {{ message.sent_date }}
            </p>
          </div>
        </div>
        {% endif %}
        {% endif %}
        {% endfor %}

      </div>

      <!-- Typing area -->
      <div class="bg-light">
        <div class="input-group">
          <input type="text" id="message-input" placeholder="Type a message" aria-describedby="button-addon2"
            class="form-control rounded-0 border-0 py-4 bg-light">
          <div class="input-group-append">
            <button id="message-send" type="submit" class="btn btn-link h-100"> <i class="fa fa-paper-plane"
                style="font-size: 1.4rem;"></i></button>
          </div>
        </div>
      </div>

    </div>

    <!-- Control Panel -->
    <div class="col-md-2 pt-3">
      <div class="list-group gap-3" id="list-tab" role="tablist">
        {% if request.user == chat.seller %}

          {% if chat.done_deal_requested %}
            <div class="btn btn-success">
              <p class="h6" style="word-break: normal;">{% trans "You've requested customer to mark this deal as DONE" %}</p>
              <a href="{% url 'chats:request_done_deal_cancel' chat.id %}" class="btn btn-danger text-decoration-underline">{% trans 'Cancel' %}</a>
            </div>
          {% else %}
          <a href="{% url 'chats:request_done_deal' chat.id %}"
            class="list-group-item list-group-item-action bg-success text-light text-decoration-underline fw-bold py-3"
            data-toggle="list" role="tab">{% trans 'Mark Deal as Done!' %}</a>
          {% endif %}

        {% else %}
          {% if chat.done_deal_requested %}
            <div class="btn btn-dark">
              <p class="h6" style="word-break: normal;">{% trans 'Seller requested you to mark this deal as DONE. Have you received product from the seller?' %}</p>
              <a href="{% url 'chats:confirm_deal' chat.id %}" class="btn btn-success text-decoration-underline">{% trans 'YES, CONFIRM DEAL' %}</a>
            </div>
          {% endif %}
        {% endif %}
        <a href="{% url 'chats:delete' chat.id %}"
          class="list-group-item list-group-item-action bg-secondary text-light fw-bold py-3" data-toggle="list"
          role="tab">{% trans 'Abort' %}</a>
        <a href="{% url 'users:report' chatting_with_id %}"
          class="list-group-item list-group-item-action bg-danger text-light fw-bold py-3" data-toggle="list"
          role="tab">{% trans 'Report User' %}</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block javascript %}
<script>
  $("#messages-list").stop().animate({
    scrollTop: $("#messages-list")[0].scrollHeight
  }, 750);
  const messageInput = document.querySelector("#message-input")
  const messageSendBtn = document.querySelector("#message-send")
  const messagesListDiv = document.querySelector("#messages-list")

  const authorId = '{{ request.user.id }}'
  const receiverId = '{{ request.user.id }}'
  const userName = '{{ request.user.first_name }}'
  const chatId = '{{ chat.id }}';
  // {% if debug %}
  var prefix = 'ws://'
  // {% else %}
  var prefix = 'wss://'
  // {% endif %}
  const chatSocket = new WebSocket(
    prefix +
    window.location.host +
    '/ws/chats/' +
    chatId +
    '/'
  );

  chatSocket.onmessage = function (event) {
    let data = JSON.parse(event.data);
    let newMessageDiv = document.createElement("div");
    if (data.authorId == authorId) {
      newMessageDiv.className = "media w-50 ms-auto mb-3"
      newMessageDiv.innerHTML = `
				<div class="media-body">
					<div class="bg-primary rounded py-2 px-3 mb-1">
						<p class="text-small mb-0 text-white">${data.newMessageText}</p>
					</div>
					<p class="message-time small text-muted text-end">
						{% trans 'You at' %} ${data.newMessageTime}
					</p>
				</div>
			`;
    } else {
      newMessageDiv.className = "media w-50 mb-3"
      newMessageDiv.innerHTML = `
				<div class="media-body ms-1">
          <div class="bg-info rounded py-2 px-3 mb-1 d-flex justify-content-between">
							<p class="text-small mb-0 text-light">${data.newMessageText}</p>              
              <a href="/users/{{chatting_with_id}}_${data.newMessageId}/report">
                <small class="text-danger" title="{% trans 'Report User' %}">
                  <i class="fa-solid fa-hand">!</i>
                </small>
              </a>
          </div>
				</div>
				<div class="message-bottom">
					<p class="message-time small text-muted ms-2">
						${data.authorName} {% trans 'at' %} ${data.newMessageTime}
					</p>
				</div>
			`;

      // mark message as seen
      fetch(`/chats/${data.newMessageId}/read`)
        .then((response) => {})
        .then((data) => {});
    }
    messagesListDiv.appendChild(newMessageDiv);
  };

  chatSocket.onclose = function (e) {
    console.error('Chat socket closed unexpectedly');
  };

  messageInput.focus();
  messageInput.onkeyup = function (event) {
    if (event.keyCode === 13) { // enter, return
      messageSendBtn.click();
    }
  };

  messageSendBtn.onclick = function (event) {
    let newMessageText = messageInput.value;
    if (newMessageText != '') {
      chatSocket.send(JSON.stringify({
        'authorId': authorId,
        'authorName': userName,
        'newMessageText': newMessageText
      }));
      messageInput.value = '';
    }
  };
</script>

  {% if request.user == chat.customer %}
    {% if not chat.done_deal_requested %}
    <script>
      // Add listener for deal confirm
      window.setInterval('check_for_done_deal_request()', 12000);
      // Call a function every 12000 milliseconds / 12 seconds
      function check_for_done_deal_request() {
        fetch("{% url 'chats:check_for_done_deal_request' chat.id %}")
          .then((response) => {
            return response.json();
          })
          .then((data) => {
            if (data['is_requested'] == true) window.location.reload()
          });
      }
    </script>
    {% else %}
    <script>
      // Add listener for deal confirm
      window.setInterval('check_for_done_deal_request_cancel()', 15000);
      // Call a function every 15000 milliseconds / 15 seconds
      function check_for_done_deal_request_cancel() {
        fetch("{% url 'chats:check_for_done_deal_request' chat.id %}")
          .then((response) => {
            return response.json();
          })
          .then((data) => {
            if (data['is_requested'] == false) window.location.reload()
          });
      }
    </script>
    {% endif %}
  {% endif %}

  {% if request.user == chat.seller and chat.done_deal_requested %}
  <script>
    // Add listener for deal confirm
    window.setInterval('check_for_confirm_deal()', 16000);
    // Call a function every 16000 milliseconds / 16 seconds
    function check_for_confirm_deal() {
      fetch("{% url 'chats:check_for_confirm_deal' chat.customer.id %}")
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          if (data['is_confirmed'] == 'true') document.location.replace('{% url "users:dashboard" %}');
        });
    }
  </script>
  {% endif %}
{% endblock javascript %}